翻译成英语
<string name="delivery_man_im">Delivery Man Information</string>
<string name="logistics_company_im">Logistics Company Information</string>


翻译成印尼语
卖家端：
<string name="un_review">Diterima</string>
<string name="order_has_accepted">Pesanan ini telah diterima.</string>
<string name="sku_action">Sku tidak bisa dinonaktifkan secara keseluruhan.</string>
<string name="order_rejected">Pesanan ini telah ditolak.</string>
<string name="order_cancel_title">Pesanan telah dibatalkan oleh pelanggan.</string>
<string name="order_cancel_mgs">Pesanan telah dibatalkan oleh pelanggan anda.</string>
<string name="order_cancel_des">Pesanan #[%1$s] telah dibatalkan oleh pelanggan.</string>
<string name="order_expired_msg">Pesanan telah kadaluarsa karena tidak ada konfirmasi dari anda atau pembayaran pelanggan anda tidak dilakukan.</string>
<string name="order_expired_title">Pesanan sudah kadaluarsa.</string>
<string name="order_expired_des">Pesanan #[%1$s] sudah kadaluarsa.</string>
<string name="order_system_close_des">Pesanan #[%1$s] telah ditutup oleh Beli Material.</string>
<string name="order_system_close_title">Pesanan telah ditutup oleh Beli Material.</string>
<string name="order_system_close_msg">Pesanan telah ditutup Beli Material.</string>
<string name="transatuion_id">Transaksi ID:%1$s</string>
<string name="dis_activate">Nonaktifkan</string>
<string name="active">Aktifkan</string>
<string name="edit_price_and_stock_title">Edit Harga dan Stok</string>
<string name="properties">Properti</string>
<string name="type">Tipe</string>


买家端：
<string name="email">Email</string>
<string name=“old_email">Email Lama</string>
<string name=“new_email">Email Baru</string>
<string name="old_phone_number">Nomor Telepon Lama</string>
<string name="new_phone_number">Nomor Telepon Baru</string>
<string name="password_hint">6-20 karakter</string>
<string name="error_email">Mohon masukkan email yang benar.</string>
<string name=“error_username">Nama pengguna minimal 3 karakter.</string>
<string name="send_email_verifiction"> Kami telah mengirim email kepada anda. Mohon dicek kode verifikasi anda.</string>
<string name="gender">Jenis Kelamin</string>
<string name="birth">Tanggal Lahir</string>
<string name="male">Pria</string>
<string name="female">Wanita</string>
<string name="Unselected">Belum dipilih</string>
<string name="birth_header">Mengatur tanggal lahir anda</string>
<string name="bind_phone_number_success">Nomor telepon anda telah berhasil diverifikasi.</string>
<string name="email_verification">Verifikasi Email</string>
<string name="reset_password">Ubah Kata Sandi</string>
<string name="email_exists">Maaf, email ini sudah ada.</string>
<string name="email_not_exists">Maaf, email ini tidak ada.</string>
<string name="unit">Unit:</string>
<string name="voucher_promo_time"> %1$s sampai %2$s</string>
<string name="version_updata">Kami telah merilis versi baru. Mohon memperbaruinya untuk dapat pengalaman yang lebih baik.</string>
<string name="updata_btn">Memperbarui Sekarang</string>
<string name=“updata_downloading">Sedang download</string>
<string name="reason">Alasan: </string>
<string name="notify_enter_email">Masukkan email login anda di bawah ini.</string>
<string name="notice_register_send_email">Email dengan kode verifikasi telah dikirim ke email terdaftar anda.</string>
<string name="enter_code">MASUKKAN KODE</string>
<string name="verify_email">Verifikasi Email</string>
<string name="verify_phone_number">Verifikasi Nomor Telepon</string>
<string name="verify">Verifikasi</string>
<string name="resend_email">Kirim Ulang Email</string>
<string name="resend_sms">Kirim Ulang SMS</string>
<string name=“not_receive_email">Email belum diterima?</string>
<string name=“not_receive_sms">SMS belum diterima?</string>
<string name=“register_success">Daftar berhasil!</string>
<string name="you_have_a_new_notification">Anda memiliki notifikasi baru.</string>
<string name="notice_verify_phone_number">Mohon verifikasi nomor telepon anda.</string>
<string name="notice_reset_password_success">Anda telah berhasil ubah kata sandi, silahkan login.</string>
<string name="notice_change_password">Apakah Anda yakin mengubah kata sandi baru</string>
<string name="change_phone_number">Ubah Nomor Telepon</string>
<string name="change_email">Ubah Email</string>
<string name=“change_password">Ubah Kata Sandi</string>
<string name="notice_enter_email">Masukkan email baru anda di bawah ini.</string>
<string name="notice_send_email">Kami akan mengirimkan email dengan kode verifikasi untuk mengubah email anda.</string>
<string name="notice_enter_phone_number">Masukkan nomor telepon baru anda di bawah ini.</string>
<string name="notice_send_phone_number">Kami akan mengirimkan SMS dengan kode verifikasi untuk mengubah nomor telepon anda.</string>
<string name="notice_verify_password">Mohon verifikasi kata sandi anda</string>
<string name=“notice_verify_password_action">Untuk keamanan akun, kami perlu memverifikasi kata sandi anda sebelum melakukan langkah ini.</string>
<string name="notice_verify_phone_place_order">Nomor telepon anda belum diverifikasi. Mohon verifikasi nomor telepon sebelum memesan.</string>
<string name="later">Nanti</string>
<string name="verify_now">Verifikasi Sekarang</string>
<string name="promo_period">Periode Promo</string>
<string name="promo_store">Toko Promo</string>
<string name="promo_category">Kategori Promo</string>
<string name="change_delivery_address">Mengubah alamat pengiriman</string>
<string name="old_password_error">Kata sandi lama salah.</string>
<string name="notice_forget_password">Kami akan mengirimkan email dengan kode verifikasi untuk mengubah kata sandi anda..</string>
<string name="notice_forget_password_send_email">Email dengan kode verifikasi telah dikirim ke email login anda.</string>
<string name="notice_change_email_send_email">Email dengan kode verifikasi telah dikirim ke email baru anda.</string>
<string name="notice_bind_phone_send_sms">SMS dengan kode verifikasi telah dikirim ke telepon anda.</string>
<string name=“notice_same_email">Maaf, email baru yang dimasukkan tidak boleh sama dengan email lama.</string>
<string name=“notice_same_phone">Maaf, nomor telepon baru yang dimasukkan tidak boleh sama dengan nomor telepon lama.</string>
<string name="notice_same_password">Maaf, kata sandi baru yang dimasukkan tidak boleh sama dengan kata sandi lama.</string>
<string name="unverified">Belum diverifikasi</string>
<string name="product_status_change">Status produk telah berubah</string>
<string name="notice_product_status_change">Anda memiliki beberapa produk dengan status \ ‘Tidak Bisa Dibeli \'. Mohon kembali ke halaman sebelumnya.</string>
<string name="already_accepted_order">Pesanan anda telah diterima oleh penjual</string>
<string name="already_accepted_order_des">Pesanan #[%1$s] telah diterima oleh [%2$s].</string>
<string name=“accepted_order_msg">Pesanan anda telah diterima oleh [%1$s]. Mohon melakukan pembayaran anda dalam 24 jam.</string>
<string name="refund_alread_complete_title">Permintaan pengembalian dana anda telah selesai.</string>
<string name="refund_alread_complete_des">Pesanan #[%1$s] yang anda minta pengembalian dana telah selesai.</string>
<string name="payment_sucess_title">Pembayaran Berhasil</string>
<string name="payment_sucess_des">[%1$s] akan mengirimkan produk ke alamat pengiriman anda.</string>
<string name="payment_sucess_msg">Pembayaran anda telah berhasil. Mohon tunggu pengirimannya dari [%1$s].</string>
<string name="order_system_close_title">Pesanan anda telah ditutup oleh Beli Material.</string>
<string name="order_system_close_des">Pesanan #[%1$s] telah ditutup oleh Beli Material.</string>
<string name=“order_system_close_msg">Pesanan anda dari [%1$s] telah ditutup oleh Beli Material.</string>
